apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test-new
  namespace: vault
  labels:
    app: read-vault-secret-new
spec:
  selector:
    matchLabels:
      app: read-vault-secret-new
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-my-first-secret: "test/db"
        vault.hashicorp.com/agent-inject-template-my-first-secret: |
          {{- with secret "test/db" -}}
          username={{ .Data.data.username }}
          password={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
      labels:
        app: read-vault-secret-new
    spec:
      serviceAccountName: vault-serviceaccount  # Must have access to Vault
      containers:
        - name: app
          image: sarthak8564/test-vault:latest  # Replace with your actual image
          command: ["sh", "-c", "python app.py && sleep infinity"]
